subject fixed

diff --git a/email-files/email-file b/email-files/email-file
--- a/email-files/email-file
+++ b/email-files/email-file
@@ -10,10 +10,10 @@ usage(){
 }
 
 user_confirmation(){
-        echo "WARNING!!!: $1"
-        echo "¿Do you want to proceed? (Write 'YES' in uppercase to continue)"
+        echo "$1"
+	echo "¿Do you want to proceed? (Y/N)"
         read a
-        [ "$a" = "YES" ] || die "Aborted due to user input"
+        [ "$a" = "YES" ] || [ "$a" = "Y" ] || [ "$a" = "yes" ] || [ "$a" = "y" ] || die "Aborted due to user input"
 }
 
 get_from_db(){
@@ -31,7 +31,8 @@ get_login_names(){
 
 get_profes(){
 	SQL="use simple_itaca; SELECT login FROM profesores_pm WHERE activo='1';"
-	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u
+#	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u
+	for l in svillanuevag lgarciag; do echo $l; done
 
 }
 
@@ -48,6 +49,8 @@ get_grupos(){
 # check configuration files
 [ -r $HOME/.my.cnf ] || die "Missing mysql configurarion in $HOME/.my.cnf"
 
+[ -r $HOME/.muttrc ] || die "Missing mutt configurarion in $HOME/.muttrc"
+
 PDF_DIR="$1"
 
 [ "$1" ] || usage
@@ -60,10 +63,19 @@ MSG_TXT="$1"
 [ -s "$MSG_TXT" ] || die "Message file invalid"
 shift
 [ "$1" ] || usage
-SUBJECT="$*"
+SUBJECT=$*
 
 PROCESSMAKER="-h 172.24.0.10"
 
+echo "Please, verify the email message"
+echo ""
+echo "======================================================================================="
+echo "SUBJECT: $SUBJECT"
+echo ""
+cat $MSG_TXT
+echo "======================================================================================="
+
+user_confirmation
 
 get_profes |while read profe; do
 	LISTA_GRUPOS="$(get_grupos "$profe")"
@@ -71,15 +83,17 @@ get_profes |while read profe; do
 	LISTA_PDF=""
 	for g in $LISTA_GRUPOS; do
 		LISTA_PDF="$LISTA_PDF $(ls -1 $PDF_DIR/${g}_Eval*.pdf 2>/dev/null)"
-#		ls -1 $PDF_DIR/${g}_Eval*.pdf 2>/dev/null
 	done
 	if ! echo "$LISTA_PDF" |grep -q "^[[:blank:]]*$" ; then
-		EMAIL_CMD="mutt -s "
+		EMAIL_CMD1="mutt"
+		EMAIL_CMD2="$profe@ausiasmarch.net "
+		FILE_LIST=""
 		for f in $LISTA_PDF; do
-
-		echo "$profe@ausiasmarch.net : $LISTA_PDF"
-	else
-		echo "$profe: SIN PDFs"
+			EMAIL_CMD2="$EMAIL_CMD2 -a $f"
+			FILE_LIST="$FILE_LIST $(basename "$f")"
+		done
+		echo "Sending to $profe files: $FILE_LIST"
+		#REPLYTO="tic@ausiasmarch.net" $EMAIL_CMD1 -s "$SUBJECT" $EMAIL_CMD2 < $MSG_TXT
 	fi
 done
 
