Added mails for departments

diff --git a/email-files/email-file b/email-files/email-file
--- a/email-files/email-file
+++ b/email-files/email-file
@@ -1,19 +1,22 @@
 #!/bin/sh
 # common code ...
+#requires: zip mysql-client
+
 die() {
         echo "$1" >&2
         exit 1
 }
 
 usage(){
-	die "Usage: $(basename "$0") PDF_DIR MSG_TXT SUBJECT"
+	die "Usage: $(basename "$0") PDF_DIR MSG_DIR SUBJECT"
 }
 
 user_confirmation(){
-        echo "$1"
+	preview_message "$1"
 	echo "¿Do you want to proceed? (Y/N)"
         read a
-        [ "$a" = "YES" ] || [ "$a" = "Y" ] || [ "$a" = "yes" ] || [ "$a" = "y" ] || die "Aborted due to user input"
+        [ "$a" = "YES" ] || [ "$a" = "Y" ] || [ "$a" = "yes" ] || [ "$a" = "y" ] || return 1
+	return 0
 }
 
 get_from_db(){
@@ -32,7 +35,9 @@ get_login_names(){
 get_profes(){
 	SQL="use simple_itaca; SELECT login FROM profesores_pm WHERE activo='1';"
 #	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u
-	for l in svillanuevag lgarciag; do echo $l; done
+#	for l in svillanuevag lgarciag; do echo $l; done
+#	for l in svillanuevag; do echo $l; done
+	cat lista-pendientes
 
 }
 
@@ -40,6 +45,42 @@ get_grupos(){
 	PROFE="$1"
 	SQL="use simple_itaca; SELECT grupo FROM grupoasiprof_pm WHERE login='$PROFE';"
 	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u
+
+}
+
+get_group_by_fam(){
+	FAMILIA="$1"
+	SQL="use simple_itaca; SELECT codigo FROM grupos_pm WHERE familia='$FAMILIA';"
+	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u
+}
+
+send_mail(){
+	EMAIL_ADDRESS="$1"
+	SUBJECT="$2"
+	MSG_TXT="$3"
+	shift 3
+	EMAIL_CMD1="mutt"
+	EMAIL_CMD2="${EMAIL_ADDRESS}@ausiasmarch.net "
+	FILE_LIST=""
+	for f in "$@"; do
+		EMAIL_CMD2="$EMAIL_CMD2 -a $f"
+		FILE_LIST="$FILE_LIST $(basename "$f")"
+	done
+	echo "Sending to $EMAIL_ADDRESS files: $FILE_LIST"
+	rc=0
+	REPLYTO="tic@ausiasmarch.net" $EMAIL_CMD1 -s "$SUBJECT" $EMAIL_CMD2 < $MSG_TXT || rc=$?
+	return $rc
+}
+
+preview_message(){
+	MSG_TXT="$1"
+	echo "Please, verify the email message for $(basename $MSG_TXT)"
+	echo ""
+	echo "======================================================================================="
+	echo "SUBJECT: $SUBJECT"
+	echo ""
+	cat $MSG_TXT
+	echo "======================================================================================="
 
 }
 
@@ -59,41 +100,56 @@ PDF_DIR="$1"
 [ $(ls "$PDF_DIR/" |grep "^[[:digit:]][[:alpha:]]\{4\}_Eval.*\.pdf$" |wc -l) -gt 0 ] || die "There is no pdf files in directory"
 shift
 [ "$1" ] || usage
-MSG_TXT="$1"
-[ -s "$MSG_TXT" ] || die "Message file invalid"
+MSG_DIR="$1"
+PROF_TXT="$MSG_DIR/profesores.txt"
+JDEP_TXT="$MSG_DIR/jdep.txt"
+DIRE_TXT="$MSG_DIR/direccion.txt"
+[ -d "$MSG_DIR" ] || die "Message directory invalid"
+[ -s "$PROF_TXT" ] || die "Message file invalid (profesores)"
+[ -s "$JDEP_TXT" ] || die "Message file invalid (jdep)"
+[ -s "$DIRE_TXT" ] || die "Message file invalid (direccion)"
+
 shift
 [ "$1" ] || usage
 SUBJECT=$*
 
 PROCESSMAKER="-h 172.24.0.10"
+LISTA_FAM="SAN,capsan COM,capcom ADM,capadm INF,capinf"
+LISTA_DIR="capestudis"
 
-echo "Please, verify the email message"
-echo ""
-echo "======================================================================================="
-echo "SUBJECT: $SUBJECT"
-echo ""
-cat $MSG_TXT
-echo "======================================================================================="
-
-user_confirmation
-
-get_profes |while read profe; do
-	LISTA_GRUPOS="$(get_grupos "$profe")"
-	#echo "$profe: $LISTA_GRUPOS"
-	LISTA_PDF=""
-	for g in $LISTA_GRUPOS; do
-		LISTA_PDF="$LISTA_PDF $(ls -1 $PDF_DIR/${g}_Eval*.pdf 2>/dev/null)"
-	done
-	if ! echo "$LISTA_PDF" |grep -q "^[[:blank:]]*$" ; then
-		EMAIL_CMD1="mutt"
-		EMAIL_CMD2="$profe@ausiasmarch.net "
-		FILE_LIST=""
-		for f in $LISTA_PDF; do
-			EMAIL_CMD2="$EMAIL_CMD2 -a $f"
-			FILE_LIST="$FILE_LIST $(basename "$f")"
+if user_confirmation $PROF_TXT; then
+	get_profes |while read profe; do
+		LISTA_GRUPOS="$(get_grupos "$profe")"
+		#echo "$profe: $LISTA_GRUPOS"
+		LISTA_PDF=""
+		for g in $LISTA_GRUPOS; do
+			LISTA_PDF="$LISTA_PDF $(ls -1 $PDF_DIR/${g}_Eval*.pdf 2>/dev/null)"
 		done
-		echo "Sending to $profe files: $FILE_LIST"
-		#REPLYTO="tic@ausiasmarch.net" $EMAIL_CMD1 -s "$SUBJECT" $EMAIL_CMD2 < $MSG_TXT
-	fi
-done
+		if ! echo "$LISTA_PDF" |grep -q "^[[:blank:]]*$" ; then
+			send_mail "$sprofe" "$SUBJECT" "$PROF_TXT" $LISTA_PDF
+		fi
+	done
+fi
 
+if user_confirmation $JDEP_TXT; then
+
+	TMP_DIR="$(mktemp -d)"
+
+	for i in $LISTA_FAM; do
+		FAMILIA=${i%,*}
+		JDEP=${i#*,}
+		echo $FAMILIA $JDEP
+		LISTA_PDF=""
+		for g in $(get_group_by_fam $FAMILIA); do
+			LISTA_PDF="$LISTA_PDF $(ls -1 $PDF_DIR/${g}_Eval*.pdf 2>/dev/null)"
+		done
+		if ! echo "$LISTA_PDF" |grep -q "^[[:blank:]]*$" ; then
+			ZIP_FILE="$TMP_DIR/actas_eval_$FAMILIA_$(date "+%m-%Y").zip"
+			zip -r -j $ZIP_FILE $LISTA_PDF >/dev/null
+			send_mail "$JDEP" "$SUBJECT" "$JDEP_TXT" "$ZIP_FILE"
+		fi
+	done
+	rm -fr "$TMP_DIR"
+fi
+
+#TODO: falta hacer el bloque de los jefes de estudios
